trigger:
  - BranchPipeline

parameters:
  - name: cucumberTags
    displayName: "Cucumber Tags to Run"
    type: string
    default: "@Smoke"
    values:
      - '@Smoke'
      - '@Regression'

pool:
  name: Default

stages:

  # =======================
  # DEV Stage
  # =======================
  - stage: DEV
    displayName: "Run Automation in DEV"
    jobs:
      - job: RunDevTests
        displayName: "Execute Tests - DEV"
        steps:
          - script: mvn clean test -Denv=dev -Dcucumber.filter.tags="${{ parameters.cucumberTags }}"
            displayName: "Run Tests in DEV with Tags"

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              testRunTitle: 'DEV Test Results'


  # =======================
  # STAGE Stage
  # =======================
  - stage: STAGE
    displayName: "Run Automation in STAGE"
    dependsOn: DEV
    condition: succeeded()
    jobs:
      - job: RunStageTests
        displayName: "Execute Tests - STAGE"
        steps:
          - script: mvn clean test -Denv=stage -Dcucumber.filter.tags="${{ parameters.cucumberTags }}"
            displayName: "Run Tests in STAGE with Tags"

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              testRunTitle: 'STAGE Test Results'