trigger:
  - BranchPipeline

pool:
  name: Default   # Self-hosted agent

stages:

  # =======================
  # DEV Stage
  # =======================
  - stage: DEV
    displayName: "Run Automation in DEV"
    jobs:
      - job: RunDevTests
        displayName: "Execute Smoke Tests - DEV"
        steps:
          - script: mvn clean test -Denv=dev
            displayName: "Run Tests in DEV"

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              testRunTitle: 'DEV Test Results'


  # =======================
  # STAGE Stage
  # =======================
  - stage: STAGE
    displayName: "Run Automation in STAGE"
    dependsOn: DEV
    condition: succeeded()     # Only run if DEV succeeds
    jobs:
      - job: RunStageTests
        displayName: "Execute Regression Tests - STAGE"
        steps:
          - script: mvn clean test -Denv=stage
            displayName: "Run Tests in STAGE"

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              testRunTitle: 'STAGE Test Results'